name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y cmake
      - name: Create build directory
        run: mkdir -p build
      - name: Run CMake
        run: cd build; cmake ..
      - name: Build
        run: make install -j `nproc --all`
